modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "sagittary"
version = "${version}"
displayName = "Sagittary"
authors = "VgLevelUp"
description = '''

'''
logoFile = "icon.png"

[[dependencies.sagittary]]
modId = "neoforge"
type = "required"
versionRange = "[26.1.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sagittary]]
modId = "minecraft"
type = "required"
versionRange = "[26.1.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.sagittary]]
modId = "architectury"
type = "required"
versionRange = "[20.0.7,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.sagittary]]
modId = "trinkets_updated"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[dependencies.sagittary]]
modId = "spelunkery"
type = "optional"
versionRange = "*"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "sagittary.mixins.json"
