minecraft_version=26.1.1
loader=fabric
java_version=25
loom_generation=current
architectury_api_version=20.0.4
fabric_loader_version=0.19.3
jei_version=29.4.0.23
fabric_api_version=0.145.4+26.1.1
trinkets_mod_id=trinkets_updated
trinkets_dev_version=4.0.1+26.1
